### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by Glaucus-SUST** [rainorangelemon/gnn-motion-planning#4]
when i run the codes, it tells me that some datasets are missing, like:

- `FileNotFoundError: [Errno 2] No such file or directory: 'data/weights/next_ur5.pt'`
- `FileNotFoundError: [Errno 2] No such file or directory: 'maze_files/kukas_14_3000.pkl'`

and i also downloaded the datasets in link. so i wonder if i lost some of the datasets or did you change some of their names? Thanks.

**Comment by rainorangelemon** [comment]
Thanks for reminding me. The weights for NEXT and the pkl files for the environment settings are uploaded. Please check.

Happy new year,
Chenning
