### ISSUE TITLE
How should I generate my own dataset?

### ISSUE THREAD

**Issue by rangfeng1** [rainorangelemon/gnn-motion-planning#8]
How should I generate my own dataset?Can you provide the corresponding files and tutorials? Thank you

**Comment by rainorangelemon** [comment]
Dear rangfeng,

Thanks for asking! Currently there's no script available for data generation. You can implement it yourself. Please refer to this issue for the basic logic for dataset generation:

https://github.com/rainorangelemon/gnn-motion-planning/issues/3#issuecomment-1309544931
